In [1]:
# coding:utf-8
import arrow
import qgrid
import seaborn as sns
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
%matplotlib inline

sns.set(style='whitegrid')

In [17]:
trans_prov_allcount = pd.read_csv("h.csv",encoding='utf-8',index_col = False, delimiter=',' )
trans_prov_allcount.head()

,index_col,stock_code,shortname,fullname,address,income,profit,number,comedate,book,report,industry,bussiness
0,1,HK0001,长和,长江和记实业有限公司,开曼群岛,--,--,288562,2015-03-18,--,NaN,综合,从事港口及相关服务、零售、基建、能源以及电讯行业。
1,2,HK0002,中电控股,中电控股有限公司,香港,--,--,7542,1980-01-02,--,NaN,电力,为香港、印度和澳洲的发电及供电业务，同时投资于中国内地、东南亚及台湾的电力项目。
2,3,HK0003,香港中华煤气,香港中华煤气有限公司,香港,--,--,2011,1960-04-11,--,NaN,燃气,于香港及中国从事燃气生产、输送与销售、供水以及经营新兴环保能源业务；于香港从事物业发展及投资活动。
3,4,HK0004,九龙仓集团,九龙仓集团有限公司,香港,--,--,13300,1921-01-01,--,NaN,地产投资,投资物业、发展物业、酒店、物流和通讯、媒体及娱乐。
4,5,HK0005,汇丰控股,汇丰控股有限公司,英国,--,--,228687,1980-01-02,--,NaN,银行,提供全面之银行及有关之金融服务。国际网络遍布亚太区、欧洲、美洲、中东及非洲。

In [18]:
trans_prov_allcount = trans_prov_allcount.drop(['index_col','address','income','profit','number','comedate','book','report','bussiness'],axis=1)

In [19]:
trans_prov_allcount= trans_prov_allcount.drop_duplicates()
trans_prov_allcount.head()

  stock_code shortname    fullname industry
0     HK0001        长和  长江和记实业有限公司       综合
1     HK0002      中电控股    中电控股有限公司       电力
2     HK0003    香港中华煤气  香港中华煤气有限公司       燃气
3     HK0004     九龙仓集团   九龙仓集团有限公司     地产投资
4     HK0005      汇丰控股    汇丰控股有限公司       银行

In [20]:
trans_prov_allcount = trans_prov_allcount.drop([20],axis=0)

In [21]:
trans_prov_allcount.to_csv("h_tmp.csv",index=0)